dist: trusty

language: node_js

node_js:
  - '8'

addons:
  apt:
    source:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directiories:
    - ./node_modules

install: npm install

script:
  - npm run test:lib
